# Generated by Django 3.2.13 on 2023-09-22 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230826_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='dw_artigos',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
